package com.stpl.assignment.model;
// Generated Jul 18, 2017 2:50:32 PM by Hibernate Tools 4.0.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Karthick generated by hbm2java
 */
@Entity
@Table(name = "student", schema = "dbo", catalog = "BPIGTN_TRAINEE")
public class StudentBean implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int studentid;
	private String studentname;
	private Integer studentmark;

	public StudentBean() {
	}

	public StudentBean(int studentid) {
		this.studentid = studentid;
	}

	public StudentBean(int studentid, String studentname, Integer studentmark) {
		this.studentid = studentid;
		this.studentname = studentname;
		this.studentmark = studentmark;
	}

	@Id

	@Column(name = "studentid", unique = true, nullable = false)
	public int getStudentid() {
		return this.studentid;
	}

	public void setStudentid(int studentid) {
		this.studentid = studentid;
	}

	@Column(name = "studentname", length = 12)
	public String getStudentname() {
		return this.studentname;
	}

	public void setStudentname(String studentname) {
		this.studentname = studentname;
	}

	@Column(name = "studentmark")
	public Integer getStudentmark() {
		return this.studentmark;
	}

	public void setStudentmark(Integer studentmark) {
		this.studentmark = studentmark;
	}

}
